version: '3'

services:

  web:
    build: ./flask
    container_name: flask
    restart: always
    expose:
      - 8080
    depends_on:
      # build db image first
      - db
    links:
      # network connection with these services
      - db
    networks:
      - backend-network
      - frontend-network

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - '80:80'
    networks:
      - frontend-network

  db:
    image: mysql:5.7
    container_name: db
    hostname: db
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
    restart: unless-stopped
    environment:
      # credentials
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: calculations
      MYSQL_USER: jakkam
      MYSQL_PASSWORD: password
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    networks:
      - backend-network

volumes:
  # just a persistance data
  mysql-data:
networks:
  backend-network:
  frontend-network:
    